'use strict';

// Our configuration composer; the client-side resource parser remains upstream.
const PARSER_URL = 'https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/resource-parser.js';
const UPSTREAM_BASE = 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX';

// Specific services precede broad vendor lists. A hidden group still has rules.
const SERVICES = Object.freeze([
  { id: 'ChatGPT', upstream: 'OpenAI', parent: 'AI' },
  { id: 'Claude', upstream: 'Claude', parent: 'AI' },
  { id: 'Gemini', upstream: 'Gemini', parent: 'AI' },
  { id: 'Copilot', upstream: 'Copilot', parent: 'AI' },
  { id: 'AI' },
  { id: 'YouTube', upstream: 'YouTube', parent: 'Google' },
  { id: 'Telegram', upstream: 'Telegram' },
  { id: 'TikTok', upstream: 'TikTok' },
  { id: 'Netflix', upstream: 'Netflix' },
  { id: 'Spotify', upstream: 'Spotify' },
  { id: 'AppleTV', upstream: 'AppleTV' },
  { id: 'AppleNews', upstream: 'AppleNews' },
  { id: 'Microsoft', upstream: 'Microsoft', direct: true },
  { id: 'Apple', upstream: 'Apple', direct: true },
  { id: 'Google', upstream: 'Google' },
].map(Object.freeze));
const PRESETS = Object.freeze({
  recommended: Object.freeze(['AI', 'YouTube', 'Telegram', 'TikTok', 'Apple', 'Google']),
  extended: Object.freeze(SERVICES.map(service => service.id)),
});

function selectedGroups(groups) {
  if (!Array.isArray(groups)) throw new Error('groups must be an array');
  const known = new Set(SERVICES.map(service => service.id));
  const selected = new Set();
  for (const group of groups) {
    if (!known.has(group)) throw new Error(`Unknown group: ${group}`);
    if (selected.has(group)) throw new Error(`Duplicate group: ${group}`);
    selected.add(group);
  }
  return selected;
}

function servicePolicy(service, selected) {
  if (selected.has(service.id)) return service.id;
  if (service.parent && selected.has(service.parent)) return service.parent;
  return service.direct ? '🎯Direct' : 'Proxies';
}

function resource(base, name, policy, tag) {
  return `${base}/${name}/${name}.list, tag=${tag}, force-policy=${policy}, update-interval=86400, enabled=true`;
}

function renderConfig(groups = PRESETS.recommended) {
  const selected = selectedGroups(groups);
  const policies = [
    'static=Proxies, server-tag-regex=.*',
    'static=🎯Direct, direct',
    'static=AdBlock, reject, direct',
    'static=Hijacking, reject, direct',
  ];
  // Declare selected parent groups before their children.
  const ordered = [];
  const added = new Set();
  function add(service) {
    if (!selected.has(service.id) || added.has(service.id)) return;
    if (service.parent) add(SERVICES.find(candidate => candidate.id === service.parent));
    added.add(service.id);
    ordered.push(service);
  }
  for (const service of SERVICES) add(service);
  for (const service of ordered) {
    if (!selected.has(service.id)) continue;
    const parent = service.parent && selected.has(service.parent) ? service.parent : 'Proxies';
    const candidates = service.direct ? ['🎯Direct', 'Proxies'] : [parent, '🎯Direct'];
    // Let a service use its own node without changing the global selection.
    policies.push(`static=${service.id}, ${candidates.join(', ')}, server-tag-regex=.*`);
  }
  policies.push('static=✈️Final, Proxies, 🎯Direct');
  const filters = [
    'FILTER_LAN, tag=LAN, force-policy=direct, inserted-resource=true, enabled=true',
    resource(UPSTREAM_BASE, 'Hijacking', 'Hijacking', 'Upstream-Hijacking'),
    resource(UPSTREAM_BASE, 'AdvertisingLite', 'AdBlock', 'Upstream-Advertising'),
  ];
  for (const service of SERVICES) {
    const policy = servicePolicy(service, selected);
    if (service.upstream) filters.push(resource(UPSTREAM_BASE, service.upstream, policy, `Upstream-${service.upstream}`));
  }
  filters.push(
    resource(UPSTREAM_BASE, 'Global', 'Proxies', 'Upstream-Global'),
    resource(UPSTREAM_BASE, 'China', 'direct', 'Upstream-China'),
    'FILTER_REGION, tag=China-IP, force-policy=direct, inserted-resource=true, enabled=true',
  );
  return `# QuantumultX-Rules — 完整配置 / Complete configuration
# Generated by scripts/generate_profiles.js. Customize on your device.
# 使用指南: https://github.com/lonecoding/QuantumultX-Rules/blob/main/docs/profiles.md
# 面向中国大陆日常使用；订阅须自行添加。Mainland China defaults.
# 1. 在 [server_remote] 添加自己的订阅并刷新资源。
# 2. 在 Proxies 选择可用节点，使用规则分流模式。
# 3. 服务组默认跟随 Proxies；Apple / Microsoft 默认直连。
# AdBlock 控制广告，Hijacking 控制防劫持；各自 reject 拦截 / direct 放行。
# 🎯Direct 固定直连；AppleTV / AppleNews 默认代理，Copilot 默认跟随 AI。
# 分流列表直接引用上游；局域网与国内 IP 使用客户端内置资源。
# YouTube 默认跟随 Google；自定义配置未选 Google 组时跟随 Proxies。
# Group selection changes controls, not rule coverage.
# Rules may overlap; verify actual matches in Quantumult X request logs.
# 本地改动请先备份；重新导入整份配置可能覆盖订阅及自定义内容。

[general]
resource_parser_url=${PARSER_URL}
network_check_url=http://www.apple.com/library/test/success.html
server_check_url=http://www.gstatic.com/generate_204
server_check_timeout=5000
excluded_routes=10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.168.0.0/16,224.0.0.0/4,255.255.255.255/32
dns_exclusion_list=*.local,localhost

[dns]
# 保留系统 DNS，额外使用以下 DNS；no-ipv6 关闭隧道 DNS 的 AAAA 应答。
no-ipv6
server=223.5.5.5
server=119.29.29.29

[policy]
${policies.join('\n')}

[server_remote]
# 将下一行取消注释，并把 example.com 地址替换为你的订阅链接。
# https://example.com/subscription, tag=Servers, update-interval=86400, opt-parser=true, enabled=true
# 多个订阅分别填写一行，使用不同 tag；原生 QX 订阅可省略 opt-parser=true。

[server_local]

[filter_remote]
${filters.join('\n')}

[filter_local]
# 在这里添加经过确认的精确域名例外；请使用上方已有的策略名称。
# host, example.com, direct
final, ✈️Final

[rewrite_remote]

[rewrite_local]

[task_local]

[mitm]
`;
}

module.exports = { PARSER_URL, UPSTREAM_BASE, SERVICES, PRESETS, renderConfig };
