#!/usr/bin/env python3
"""Generate the legacy advertising subscription from its canonical source."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "rules/Advertising/Advertising.list"
DESTINATION = ROOT / "adblock.list"


def render_compat(source: Path = SOURCE) -> str:
    return (
        "# Generated by scripts/generate_compat.py; do not edit this file.\n"
        "# Edit rules/Advertising/Advertising.list and regenerate instead.\n"
        + source.read_text(encoding="utf-8")
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check without writing")
    args = parser.parse_args()
    expected = render_compat()
    current = DESTINATION.read_text(encoding="utf-8") if DESTINATION.is_file() else None
    if current == expected:
        print("Compatibility advertising list is up to date.")
        return 0
    if args.check:
        print("Regeneration required: adblock.list. Run python scripts/generate_compat.py.")
        return 1
    DESTINATION.write_text(expected, encoding="utf-8", newline="\n")
    print("Updated: adblock.list")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
