#!/usr/bin/env python3
"""Generate the optional daily template with three upstream rule subscriptions."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UPSTREAM_BASE = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX"
UPSTREAM_POLICIES = {"Hijacking": "reject", "Global": "Proxies", "China": "direct"}
RESOURCE_PARSER_URL = "https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/resource-parser.js"


def upstream_line(name: str) -> str:
    return (
        f"{UPSTREAM_BASE}/{name}/{name}.list, tag={name}, "
        f"force-policy={UPSTREAM_POLICIES[name]}, update-interval=86400, enabled=true"
    )


def render_daily(root: Path = ROOT) -> str:
    base = (root / "config/full.conf").read_text(encoding="utf-8")
    _, general = base.split("[general]", 1)
    settings, filters = general.split("[filter_remote]", 1)
    settings = "\nresource_parser_url=" + RESOURCE_PARSER_URL + settings
    settings = settings.replace(
        "# https://example.com/subscription, tag=Servers, update-interval=86400, enabled=true",
        "# https://example.com/subscription, tag=Servers, update-interval=86400, opt-parser=true, enabled=true",
    )
    remote, local = filters.split("[filter_local]", 1)
    lines = remote.strip().splitlines()
    lan = [i for i, line in enumerate(lines) if line.split(",", 1)[0].endswith("/rules/LAN/LAN.list")]
    if len(lan) != 1:
        raise ValueError("full.conf must import exactly one LAN list")
    # Keep LAN before blocking, and specific services before broad upstream lists.
    lines.insert(lan[0] + 1, upstream_line("Hijacking"))
    lines.extend([upstream_line("Global"), upstream_line("China")])
    return (
        "# QuantumultX-Rules daily configuration template\n"
        "# Generated by scripts/generate_daily.py; do not edit this file.\n"
        "# Repository: https://github.com/lonecoding/QuantumultX-Rules\n"
        "# Uses upstream blackmatrix7 Hijacking, Global and China lists.\n"
        "# Uses the upstream KOP-XIAO resource parser for opt-parser=true resources.\n"
        "# Add your own subscriptions on your device; none are included here.\n"
        "# China-list matches use direct; Global-list matches use Proxies.\n"
        "# Unmatched traffic uses Final; this template adds no GeoIP/FILTER_REGION rule.\n"
        "# See docs/upstream-rules.md for sources, updates and verification limits.\n\n"
        "[general]" + settings + "[filter_remote]\n" + "\n".join(lines)
        + "\n\n[filter_local]" + local
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check without writing")
    args = parser.parse_args()
    path = ROOT / "config/daily.conf"
    expected = render_daily()
    current = path.read_text(encoding="utf-8") if path.is_file() else None
    if current == expected:
        print("Daily template is up to date (3 upstream subscriptions).")
        return 0
    if args.check:
        print("Regeneration required: config/daily.conf. Run python scripts/generate_daily.py.")
        return 1
    path.write_text(expected, encoding="utf-8", newline="\n")
    print("Updated: config/daily.conf")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
